vs2010/Chapter9/Chapter9_JQueryMobile/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace Chapter9_JQueryMobile.Controllers
{
  public class ViewSwitcherController : Controller
  {
    public RedirectResult SwitchView(bool mobile, string mobileType, 
      string returnUrl)
    {
      mobileType = (mobileType == null) ? 
        string.Empty : mobileType.Trim().ToLower();
      if (mobileType == "default")
      {
        HttpContext.ClearOverriddenBrowser();
      }
      else
      {
        if (mobileType == string.Empty) mobileType = "mobile";
        switch (mobileType)
        {
          case "desktop":
            HttpContext.SetOverriddenBrowser("Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.5 Safari/534.55.3");
            break;
          case "tablet":
          case "ipad":
            HttpContext.SetOverriddenBrowser("Mozilla/5.0 (iPad; U; CPU OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5");
            break;
          case "phone":
          case "iphone":
            HttpContext.SetOverriddenBrowser("Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5");
            break;
          default:
            HttpContext.SetOverriddenBrowser(BrowserOverride.Mobile);
            break;
        }
      }
      return Redirect(returnUrl);
    }
  }
}

vs2010/Chapter9/Chapter9_JQueryMobile/Views/Shared/_Layout.Phone.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

        @Styles.Render("~/Content/MobileCSS")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/MobileJS")

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>  

  <meta name="apple-touch-fullscreen" content="no" /> 
  <meta name="apple-mobile-web-app-capable" content="no" /> 
  @*<script type="text/javascript" src="@Url.Content("~/Scripts/PromptForBookmark.js")" ></script>*@

  <!-- iPhone Low-Res -->
  <link rel="apple-touch-icon-precomposed" sizes="57x57"   href="~/Content/images/apple-touch-icon-57x57.png" />
  <!-- iPhone Hi-Res -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/images/apple-touch-icon-114x114.png" /> 
  <!-- Android -->
  <link rel="apple-touch-icon-precomposed" sizes="android-only" href="~/Content/images/apple-touch-icon-57x57.png" />   
  <!-- default -->
  <link rel="apple-touch-icon-precomposed" href="~/Content/images/apple-touch-icon-57x57.png" />   

  <!-- iPhone Low-Res -->
  <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_320x460.png" media="(device-width: 320px)" /> 
  <!-- iPhone Retina -->
  <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_640x920.png" media="(device-width: 640px) and (-webkit-device-pixel-ratio: 2)" /> 
  <!-- iPhone Low-Res Landscape -->
  <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_480x300.png" media="(device-width: 320px) and (orientation: landscape)" /> 
  <!-- iPhone Retina Landscape -->
  <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_960x600.png" media="(device-width: 640px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" /> 
  <!-- (iPhone default) -->
  <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_320x460.png" /> 

    </head>
    <body>
    <div data-role="page" data-theme="b">
      <div data-role="header" data-position="fixed" data-theme="b">
        <h1>@ViewBag.Title (Phone)</h1>
      @{
        bool ShowBackButton = false;
        bool ShowHomeButton = false;
        if (ViewBag.ShowBackButton != null && 
            ViewBag.ShowBackButton == true)
        {
          ShowBackButton = true;
        }
        if (ViewBag.ShowHomeButton != null && 
            ViewBag.ShowHomeButton == true)
        {
          ShowHomeButton = true;
        }
        if (ShowBackButton)
        {
          <a data-rel="back" data-role="button" 
             data-transition="slide" data-direction="reverse" 
             data-icon="back">Back</a>
        }
        if (ShowHomeButton)
        {
          <a href="@Url.Action("Index", "Home")" data-role="button"
             data-transition="slide" data-direction="reverse" 
             data-icon="home">Home</a>
        }
      }
@Html.Partial("_NavBar")
      </div>
      <div data-role="content" data-theme="d">
@RenderSection("featured", false)
@RenderBody()
@Html.Partial("_ViewSwitcher")
      </div>
    </div>
  </bodv>
</html>

vs2010/Chapter9/Chapter9_JQueryMobile/Views/Shared/_Layout.Tablet.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/MobileCSS")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/MobileJS")

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>  

    <meta name="apple-touch-fullscreen" content="no" /> 
    <meta name="apple-mobile-web-app-capable" content="no" /> 
    @*<script type="text/javascript" src="@Url.Content("~/Scripts/PromptForBookmark.js")" ></script>*@

    <!-- iPad Low-Res -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/images/apple-touch-icon-72x72.png" />   
    <!-- iPad Hi-Res -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/images/apple-touch-icon-144x144.png" /> 
    <!-- Android -->
    <link rel="apple-touch-icon-precomposed" sizes="android-only" href="~/Content/images/apple-touch-icon-57x57.png" />   
    <!-- default -->
    <link rel="apple-touch-icon-precomposed" href="~/Content/images/apple-touch-icon-57x57.png" />   

    <!-- iPad Low-Res -->
    <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_768x1004.png" media="(device-width: 768px) and (orientation: portrait)" /> 
    <!-- iPad Retina -->
    <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_1536x2008.png" media="(device-width: 1536px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)" /> 
    <!-- iPad Low-Res Landscape -->
    <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_1024x748.png" media="(device-width: 768px) and (orientation: landscape)" /> 
    <!-- iPad Retina Landscape -->
    <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_2048x1496.png" media="(device-width: 1536px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" /> 
    <!-- (iPad default) -->
    <link rel="apple-touch-startup-image" href="~/Content/images/startup_image_768x1004.png" /> 

  </head>
  <body>
    <div data-role="page" data-theme="b">
      <div data-role="header" data-position="fixed" data-theme="b">
        <h1>@ViewBag.Title (Tablet)</h1>
      @{
        bool ShowBackButton = false;
        bool ShowHomeButton = false;
        if (ViewBag.ShowBackButton != null && 
            ViewBag.ShowBackButton == true)
        {
          ShowBackButton = true;
        }
        if (ViewBag.ShowHomeButton != null && 
            ViewBag.ShowHomeButton == true)
        {
          ShowHomeButton = true;
        }
        if (ShowBackButton)
        {
          <a data-rel="back" data-role="button" 
             data-transition="slide" data-direction="reverse" 
             data-icon="back">Back</a>
        }
        if (ShowHomeButton)
        {
          <a href="@Url.Action("Index", "Home")" data-role="button"
             data-transition="slide" data-direction="reverse" 
             data-icon="home">Home</a>
        }
      }
@Html.Partial("_NavBar")
      </div>
      <div data-role="content" data-theme="d">
@RenderSection("featured", false)
@RenderBody()
@Html.Partial("_ViewSwitcher")
      </div>
    </div>
  </bodv>
</html>

vs2010/Chapter9/Chapter9_JQueryMobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
@Html.Partial("_ViewSwitcher")
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

vs2010/Chapter9/Chapter9_JQueryMobile/Views/Shared/_NavBar.cshtml
<div data-role="navbar" data-theme="d" data-iconpos="top">
  <ul>
    <li><a href="@Url.Action("Index", "Home")" data-icon="home">Home</a></li>
    <li><a href="@Url.Action("Lists", "Home")" data-icon="custom-thought">List Examples</a></li>
    <li>@Html.ActionLink("About Us", "About", "Home", null, new { data_icon = "custom-bugimage" })</li>
  </ul>
</div>

vs2010/Chapter9/Chapter9_JQueryMobile/Views/Shared/_ViewSwitcher.cshtml
<span style="font-size: 0.7em;">
Switch To: 
@Html.ActionLink("Desktop View", "SwitchView", "ViewSwitcher", 
  new { mobile = false, mobileType = "Desktop", 
  returnUrl = Request.Url.PathAndQuery }, 
  new { rel = "external" }) 
@Html.ActionLink("Tablet View", "SwitchView", "ViewSwitcher", 
  new { mobile = true, mobileType = "Tablet", 
  returnUrl = Request.Url.PathAndQuery }, 
  new { rel = "external" }) 
@Html.ActionLink("Phone View", "SwitchView", "ViewSwitcher", 
  new { mobile = true, mobileType = "Phone", 
  returnUrl = Request.Url.PathAndQuery }, 
  new { rel = "external" }) 
@Html.ActionLink("Default View", "SwitchView", "ViewSwitcher", 
  new { mobile = false, mobileType = "Default", 
  returnUrl = Request.Url.PathAndQuery }, 
  new { rel = "external" }) 
</span>